set(COINBOX_RECOVERY_SEED_DEFAULT "test")

function(coinbox_load_recovery_seed out_seed out_seed_escaped env_file)
    set(seed "${COINBOX_RECOVERY_SEED_DEFAULT}")

    if(EXISTS "${env_file}")
        file(STRINGS "${env_file}" env_lines)
        foreach(line IN LISTS env_lines)
            string(STRIP "${line}" line)
            if(line STREQUAL "" OR line MATCHES "^#")
                continue()
            endif()
            if(line MATCHES "^COINBOX_RECOVERY_SEED[ \t]*=(.*)$")
                set(seed "${CMAKE_MATCH_1}")
                string(REGEX REPLACE "^[ \t]+" "" seed "${seed}")
                string(REGEX REPLACE "[ \t]+$" "" seed "${seed}")
                if(seed MATCHES "^\"(.*)\"$")
                    set(seed "${CMAKE_MATCH_1}")
                elseif(seed MATCHES "^'(.*)'$")
                    set(seed "${CMAKE_MATCH_1}")
                endif()
            endif()
        endforeach()
    endif()

    string(REPLACE "\\" "\\\\" seed_escaped "${seed}")
    string(REPLACE "\"" "\\\"" seed_escaped "${seed_escaped}")

    set(${out_seed} "${seed}" PARENT_SCOPE)
    set(${out_seed_escaped} "${seed_escaped}" PARENT_SCOPE)
endfunction()
